spring.application.name=springredis

#redis
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.cache.type=redis

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/sandeshdb
spring.datasource.username=sandesh
spring.datasource.password=strongpassword

# JPA
spring.jpa.hibernate.ddl-auto=update